name: CloudWatch Monitoring Project

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Show project files
        run: |
          echo "Project files:"
          ls -la
          echo "Backend:"
          ls -la backend
          echo "Frontend:"
          ls -la frontend

      - name: Test GitHub Actions
        run: echo "GitHub Actions is working successfully!"